import json
import logging
from pathlib import Path
from datetime import datetime
from src.config.settings import Config
from src.lib.locking import FileLockManager

logger = logging.getLogger(__name__)

class ApprovalManager:
    """Manages the HITL approval queue and markdown generation."""
    
    def __init__(self, dry_run: bool = None):
        self.dry_run = dry_run if dry_run is not None else Config.DRY_RUN
        self.state_file = Config.STATE_DIR / "approved_actions.json"
        
        # Ensure directories exist
        Config.STATE_DIR.mkdir(parents=True, exist_ok=True)
        Config.PENDING_APPROVAL_DIR.mkdir(parents=True, exist_ok=True)
        Config.APPROVED_DIR.mkdir(parents=True, exist_ok=True)

    def _get_queue(self) -> dict:
        """Reads the approval queue from JSON."""
        if not self.state_file.exists():
            return {"pending": {}, "completed": {}}
        
        with FileLockManager.with_lock(self.state_file):
            try:
                with open(self.state_file, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except (json.JSONDecodeError, IOError):
                logger.error(f"Failed to read approval state: {self.state_file}")
                return {"pending": {}, "completed": {}}

    def _save_queue(self, queue: dict):
        """Saves the approval queue to JSON."""
        if self.dry_run:
            return

        with FileLockManager.with_lock(self.state_file):
            with open(self.state_file, 'w', encoding='utf-8') as f:
                json.dump(queue, f, indent=2)

    def create_request(self, skill: str, action: str, description: str, 
                       input_data: dict, metadata: dict = None) -> str:
        """
        Creates an approval request markdown file and adds it to the queue.
        Returns the path to the created markdown file.
        """
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        request_id = f"REQ_{skill.upper()}_{timestamp}"
        file_name = f"{request_id}.md"
        request_path = Config.PENDING_APPROVAL_DIR / file_name

        # 1. Generate Markdown content
        content = f"""---
id: {request_id}
type: approval_request
skill: {skill}
action: {action}
created_at: {datetime.now().isoformat()}
status: pending
---

# Approval Request: {skill.replace('-', ' ').title()}

## Description
{description}

## Action Details
- **Skill**: `{skill}`
- **Action**: `{action}`
- **Request ID**: `{request_id}`

## Payload
```json
{json.dumps(input_data, indent=2)}
```

## Instructions
1. Review the action details and payload above.
2. To **APPROVE**: Move this file to the `Approved` folder.
3. To **REJECT**: Move this file to the `Rejected` folder (or delete it).

---
*Generated by Bronze Vault HITL System*
"""

        if not self.dry_run:
            # 2. Write Markdown file
            with open(request_path, 'w', encoding='utf-8') as f:
                f.write(content)

            # 3. Add to queue
            queue = self._get_queue()
            queue["pending"][request_id] = {
                "skill": skill,
                "action": action,
                "description": description,
                "input_data": input_data,
                "metadata": metadata or {},
                "created_at": datetime.now().isoformat(),
                "file_path": str(request_path.absolute())
            }
            self._save_queue(queue)
            
            logger.info(f"Created approval request: {request_id}")
        else:
            logger.info(f"[DRY_RUN] Would create approval request: {request_id}")

        return str(request_path)

    def mark_approved(self, request_id: str) -> dict:
        """Marks a request as approved in the queue and returns the action details."""
        queue = self._get_queue()
        
        if request_id not in queue["pending"]:
            logger.error(f"Request ID {request_id} not found in pending queue.")
            return None

        # Move from pending to completed
        action_details = queue["pending"].pop(request_id)
        action_details["approved_at"] = datetime.now().isoformat()
        action_details["status"] = "approved"
        
        queue["completed"][request_id] = action_details
        
        self._save_queue(queue)
        logger.info(f"Request {request_id} marked as approved in queue.")
        
        return action_details
